import { type Metadata } from "next";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";
import logo from "./imgs/maple_leaf_website_logo.png";
import { ReactNode } from "react";
import { Button } from "../components/ui/button";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >

          <header className="flex justify-center items-center p-4 gap-6 h-18 mt-4 pt-15">
            <SignedOut>
              <div className = "flex justify-center items-center p-4 gap-6 h-18 mt-8 pt-20">
              <SignInButton>
                <button className="bg-[#6c47ff] text-white rounded-full font-medium text-sm sm:text-base h-10 w-25 sm:h-12 px-4 sm:px-5 cursor-pointer bg-black hover:bg-gray-800">
                  Sign In
                </button>
              </SignInButton>
              <SignUpButton>
                <button className="bg-[#6c47ff] text-white rounded-full font-medium text-sm sm:text-base h-10 w-25 sm:h-12 px-4 sm:px-5 cursor-pointer bg-black hover:bg-gray-800">
                  Sign Up
                </button>
              </SignUpButton>
             </div> 
            </SignedOut>
            

            <SignedIn>
              <nav className="w-full flex items-center justify-start px-6 py-4 bg-white shadow-md">
                <div className="flex items-center space-x-5">
                  <Link href="/">
                    <Image
                      src={logo}
                      alt="Two Small Men Logo"
                      width={200}
                      height={100}
                      className="cursor-pointer"
                    />
                  </Link>
                  <Link href="/">
                    <h1 className="text-3xl font-bold text-gray-800 cursor-pointer ml-5">
                      Vehicle Routing Solver
                    </h1>
                  </Link>
                </div>
                <div className="flex space-x-6 ml-40">
                  <Link href="/fetch-all">
                    <Button
                      variant="default"
                      className="w-50 h-14 text-xl bg-black hover:bg-gray-800"
                    >
                      Fetch All Deals
                    </Button>
                  </Link>

                  <Link href="/fetch-id">
                    <Button
                      variant="default"
                      className="w-50 h-14 text-xl bg-black hover:bg-gray-800"
                    >
                      Fetch via Deal ID
                    </Button>
                  </Link>
                </div>
              </nav>
             <div className="mr-20"><UserButton /></div> 
            </SignedIn>
          </header>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
