import { type Metadata } from "next";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";
import logo from "./imgs/maple_leaf_website_logo.png";
import { ReactNode } from "react";
import { Button } from "../components/ui/button";
import AuthorizedNavbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >

          <header className="flex justify-center items-center p-4 gap-6 h-18 mt-4 pt-15">
            <SignedOut>
              <div className="flex flex-col items-center justify-center py-16 gap-4 mt-40">
                <h1 className="text-4xl font-bold text-gray-800 mb-2">Vehicle Routing Solver</h1>
                <div className="flex space-x-4">
                  <SignInButton>
                    <button className="bg-black text-white rounded-full font-medium text-base h-12 px-6 hover:bg-gray-800 transition">
                      Sign In
                    </button>
                  </SignInButton>
                  <SignUpButton>
                    <button className="bg-black text-white rounded-full font-medium text-base h-12 px-6 hover:bg-gray-800 transition">
                      Sign Up
                    </button>
                  </SignUpButton>
                </div>
                <p className="text-gray-600 mt-4 max-w-md text-center">
                  Welcome to the VRP Solver! Please sign in or sign up to access route tools and manage deals.
                </p>
              </div>
            </SignedOut>
            

            <SignedIn>
              <AuthorizedNavbar/>
            </SignedIn>
          </header>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
